print("일반계산기 프로그램입니다!")
a = int(input("계산할 첫번째 값을 입력해주세요 : "))
b = int(input("계산할 두번째 값을 입력해주세요 : "))

print("\n\n두 개의 값 : {} 와 {}\n".format(a,b))
print("더하기 값 (a + b) : {}".format(a+b))
print("빼기 값 ( a - b) : {}".format(a-b))
print("곱하기 값 ( a * b ) : {}".format(a*b))
print("정수 나누기 값 ( a // b ) : {}".format(a//b))
print("실수 나누기 값 ( a / b ) : {}".format(a/b))
print("나머지 값 ( a % b ) : {}".format(a%b))